package com.ktv.stb.downloader

object DownloadErrorCode {
    const val VIEW_API_FAILED = "VIEW_API_FAILED"
    const val CID_NOT_FOUND = "CID_NOT_FOUND"
    const val PLAYURL_API_FAILED = "PLAYURL_API_FAILED"
    const val UNSUPPORTED_RESOURCE_TYPE = "UNSUPPORTED_RESOURCE_TYPE"
    const val UNSUPPORTED_NON_MP4 = "UNSUPPORTED_NON_MP4"
    const val EMPTY_DURL = "EMPTY_DURL"
    const val DOWNLOAD_HTTP_FAILED = "DOWNLOAD_HTTP_FAILED"
    const val TEMP_FILE_EMPTY = "TEMP_FILE_EMPTY"
    const val MOVE_FILE_FAILED = "MOVE_FILE_FAILED"
    const val FINAL_FILE_INVALID = "FINAL_FILE_INVALID"
    const val MISSING_VIDEO_TRACK = "MISSING_VIDEO_TRACK"
    const val MISSING_AUDIO_TRACK = "MISSING_AUDIO_TRACK"
}
